## Cellosaurus

In [149]:
import xml.etree.ElementTree as ET
import pandas as pd
#Cellosaurus
tree = ET.parse('cell.xml')
root = tree.getroot()

# recorro el arbol para linea celular de xml paso por cell - line, depués a accession-list, y luego obtengo el texto del recorrido del accession.
list_cell =[]
list_syn = []

diccionario = {
 
    
    'linea celuar' : j.text,
    'sinonimos' : list_syn
}

for i in root.find('cell-line-list'):
    
    for j in i.find('accession-list'):
        #print(j.text)
       # linea_celular = (j.text)
       # print({ 'linea_celular': j.text})
      
    list_cell.append(j.text)
# recorro el árbol para sinónimos

    for k in i.find('name-list'):
     if k.get('type') == "synonym":
        list_syn.append(k.text)
    
    print({ 'linea_celular': j.text})    
    print({'sinonimos': list_syn})


diccionario = {
 
    
    'linea celuar' : j.text,
    'sinonimos' : list_syn
}
print(diccionario)
df = pd.DataFrame(diccionario)
df 
#accesion = [j.text]
#sinonimos = [list_syn]


#diccionario = {
 
    
 #   'accession' : j.text,
  #  'sinonimos' : list_syn,
#}

#df = pd.DataFrame(diccionario)
#df 
 
    
    
#df = pd.DataFrame(
# list(zip(j.text, list_syn)),
#  columns = ["accesion","sinonimos"]
#)
#df


#columns = ["sinonimos","accession"]
#df = pd.DataFrame(list_syn,j.text , columns = columns)
#df
#print (cadena)
    
#INGRESE LA LINEA CELULAR A BUSCAR 
#GUARDAR EN ALGÚN LADO
#ARROJA EL  print({'accession': j.text,'sinonimos': list_syn})
# FOR In list_syn: 
  #cadena = cadena + i + "or"
    
#cadena = j.text + cadeca
#print (cadena)

{'linea_celular': 'CVCL_B0T9'}
{'sinonimos': ['Z48-5MG-70']}
{'linea_celular': 'CVCL_B0T8'}
{'sinonimos': ['Z48-5MG-70', 'Z48-5MG-63']}
{'linea_celular': 'CVCL_E548'}
{'sinonimos': ['Z48-5MG-70', 'Z48-5MG-63', '15310-LN', 'TER461', 'TER-461', 'Ter 461', 'TER479', 'TER-479', 'Ter 479', 'Extract 519']}
{'linea celuar': 'CVCL_E548', 'sinonimos': ['Z48-5MG-70', 'Z48-5MG-63', '15310-LN', 'TER461', 'TER-461', 'Ter 461', 'TER479', 'TER-479', 'Ter 479', 'Extract 519']}

  linea celuar    sinonimos
0    CVCL_E548   Z48-5MG-70
1    CVCL_E548   Z48-5MG-63
2    CVCL_E548     15310-LN
3    CVCL_E548       TER461
4    CVCL_E548      TER-461
5    CVCL_E548      Ter 461
6    CVCL_E548       TER479
7    CVCL_E548      TER-479
8    CVCL_E548      Ter 479
9    CVCL_E548  Extract 519

## PudMed

In [28]:
import json

from Bio import Entrez

Entrez.email = 'henry.guanoluisa@epn.edu.ec'

#string_search = Entrez.read( Entrez.esearch( db="pubmed", term='("CVCL 1690" OR "SF295" OR "SF-295" OR "SF 295") AND ("cell line" OR "cell-line" OR "cellular line")' ))
#https://stackoverflow.com/questions/70647568/parse-xml-file-with-nested-elements

string_search = Entrez.read( Entrez.esearch( db="pubmed", term='("CVCL_B0T8" OR "Z48-5MG-70" OR "Z48-5MG-63") AND ("cell line" OR "cell-line" OR "cellular line")' ))

search_ids = [ int(id) for id in string_search['IdList'] ]
print(search_ids)

[36200530, 35036572, 33969526, 33453083, 33165868, 32954502, 32197467, 32133675, 31157458, 29873307, 29577375, 28815590]